In [23]:
import numpy as np
import matplotlib.pyplot as plt
from image_graph_util import img_conversion_v7
from sklearn.preprocessing import MinMaxScaler
import os
import glob
import tensorflow as tf
import tensorflow_datasets as tfds
from sklearn.model_selection import train_test_split
from emnist import extract_training_samples,extract_test_samples
from emnist import list_datasets
from sklearn.utils import shuffle

In [24]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)


In [25]:
img=img_conversion_v7.image_convert()

patch=4


In [26]:
print(list_datasets())

['balanced', 'byclass', 'bymerge', 'digits', 'letters', 'mnist']


In [27]:
train_images,train_labels=extract_training_samples('balanced')

In [28]:
test_images, test_labels = extract_test_samples('balanced')

In [29]:
#normalization of train dataset
ftrain_images = np.float16(np.array(train_images)/255)
train_labels = np.float16(np.array(train_labels))

In [30]:
#normalization of test dataset
ftest_images = np.float16(np.array(test_images)/255)
test_labels = np.float16(np.array(test_labels))

In [31]:
print(ftrain_images.shape)
print(ftest_images.shape)

(112800, 28, 28)
(18800, 28, 28)


In [32]:
# making 28,28,1
rtrain_images=ftrain_images.reshape(ftrain_images.shape[0],ftrain_images.shape[1],ftrain_images.shape[2],1)
rtest_images=ftest_images.reshape(ftest_images.shape[0],ftest_images.shape[1],ftest_images.shape[2],1)

In [33]:
print(rtrain_images.shape)
print(rtest_images.shape)

(112800, 28, 28, 1)
(18800, 28, 28, 1)


In [34]:
reg_val,reg_test,reg_val_label,reg_test_label=train_test_split(rtest_images,test_labels,test_size=0.50,random_state=42)


In [35]:
reg_train=rtrain_images
reg_train_label=train_labels


In [36]:
print(reg_train.shape)
print(reg_val.shape)
print(reg_test.shape)
print(reg_train_label.shape)
print(reg_val_label.shape)
print(reg_test_label.shape)


(112800, 28, 28, 1)
(9400, 28, 28, 1)
(9400, 28, 28, 1)
(112800,)
(9400,)
(9400,)


In [37]:
reg_train_patch=img.to_patcharray(reg_train,patch_size=(patch,patch))
reg_val_patch=img.to_patcharray(reg_val,patch_size=(patch,patch))
reg_test_patch=img.to_patcharray(reg_test,patch_size=(patch,patch))

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



####  Patch size

In [38]:
print(reg_train_patch.shape)
print(reg_val_patch.shape)
print(reg_test_patch.shape)

(112800, 1, 49, 4, 4)
(9400, 1, 49, 4, 4)
(9400, 1, 49, 4, 4)


In [39]:
from collections import Counter
#print((Counter(y_val)))
print(np.sort(list(Counter(reg_train_label).keys())))
classes=len(np.sort(list(Counter(reg_train_label).keys())))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46.]


# Laplacian image analysis

In [40]:
import networkx as nx



def compute_lap_to_gersh(df_in): #compute_lap_to_gersh
    adj_ary=np.ones(reg_train_patch.shape[-2]*reg_train_patch.shape[-1])-np.eye(reg_train_patch.shape[-2]*reg_train_patch.shape[-1])

    gersh_c=np.tile(np.sum(adj_ary,axis=0),(reg_train_patch.shape[1],reg_train_patch.shape[2]))

    edge=np.array(np.where(adj_ary==1))
    ed0=edge[0]
    ed1=edge[1]
    no_img,no_ch, no_patch,patch_x,patch_y=df_in.shape
    temp=[]
    for i in range(no_img):
        i_ary = np.eye(patch_x*patch_y)
        i_ary4d=i_ary[np.newaxis,np.newaxis,:,:]
        weighted_adj=np.zeros((no_ch, no_patch,patch_x*patch_y,patch_x*patch_y))
        df=df_in[i].reshape(no_ch,no_patch,-1)
        pixel1=df[:,:,ed0]
        pixel2=df[:,:,ed1]  
        edu_distance=np.sqrt((pixel1-pixel2)**2)+ 10**(-8)
        weighted_adj[:,:,ed0,ed1]=edu_distance
        sum_r=np.sum(weighted_adj,axis=2)
        gersh_r=sum_r.reshape(no_ch,-1)
        gersh_total=np.vstack((gersh_r[0],gersh_c[0]))
        gersh_total=gersh_total.reshape(no_ch,2,gersh_c.shape[-1])
        temp.append(gersh_total)
    return temp



In [41]:
from multiprocessing import Pool
import multiprocessing



num_cores = multiprocessing.cpu_count()
print("Number of CPU cores:", num_cores)


Number of CPU cores: 48


In [42]:
train_patch1=np.array_split(reg_train_patch[:], num_cores)
val_patch1=np.array_split(reg_val_patch[:], num_cores)
test_patch1=np.array_split(reg_test_patch[:], num_cores)

In [43]:
print(len(train_patch1))
print(len(val_patch1))
print(len(test_patch1))

48
48
48


In [44]:
with Pool(processes=num_cores) as pool:
        # Define a list of numbers
    train_p = train_patch1
    
        # Apply the square function to each number using the pool
    g_train=pool.map(compute_lap_to_gersh,train_p)
pool.close()


    
        #results = pool.map(calculate_visibility, numbers)


In [45]:
temp1=[]
for submatrix in g_train:
    temp1.extend(submatrix)


In [46]:
gersh_train= np.array([np.asarray(submatrix) for submatrix in temp1])


In [47]:
print("d")

d


In [48]:
with Pool(processes=num_cores) as pool1:
        # Define a list of numbers
    val_p = val_patch1
    
        # Apply the square function to each number using the pool
    g_val=pool1.map(compute_lap_to_gersh,val_patch1)    
pool1.close()



In [49]:
temp2=[]
for submatrix in g_val:
    temp2.extend(submatrix)


In [50]:
gersh_val= np.array([np.asarray(submatrix) for submatrix in temp2])


In [51]:
print("d")

d


In [52]:
with Pool(processes=num_cores) as pool2:
        # Define a list of numbers
    test_p = test_patch1
    
        # Apply the square function to each number using the pool
    g_test=pool2.map(compute_lap_to_gersh,test_patch1) 
pool2.close()


In [53]:
temp3=[]
for submatrix in g_test:
    temp3.extend(submatrix)


In [54]:
gersh_test= np.array([np.asarray(submatrix) for submatrix in temp3])


gersh_train=np.array(img1.to_gridlaparray(train_patch))
gersh_val=np.array(img1.to_gridlaparray(val_patch))
gersh_test=np.array(img1.to_gridlaparray(test_patch))

In [55]:
print(gersh_train.shape)
print(gersh_val.shape)
print(gersh_test.shape)

(112800, 1, 2, 784)
(9400, 1, 2, 784)
(9400, 1, 2, 784)


In [56]:
reg_train_patch.shape[-3]*reg_train_patch.shape[-2]*reg_train_patch.shape[-1]

784

In [57]:
rgersh_train=gersh_train.reshape(reg_train_patch.shape[0],2,reg_train_patch.shape[-3]*reg_train_patch.shape[-2]*reg_train_patch.shape[-1],reg_train_patch.shape[1])
rgersh_val=gersh_val.reshape(reg_val_patch.shape[0],2,reg_train_patch.shape[-3]*reg_train_patch.shape[-2]*reg_train_patch.shape[-1],reg_train_patch.shape[1])
rgersh_test=gersh_test.reshape(reg_test_patch.shape[0],2,reg_train_patch.shape[-3]*reg_train_patch.shape[-2]*reg_train_patch.shape[-1],reg_train_patch.shape[1])


In [58]:
rgersh_train.shape

(112800, 2, 784, 1)

In [59]:
print(rgersh_train.shape)
print(rgersh_train.shape)
print(rgersh_train.shape)

(112800, 2, 784, 1)
(112800, 2, 784, 1)
(112800, 2, 784, 1)


# Gershgorien 2D CNN

In [60]:
input_shape = (rgersh_train.shape[1],rgersh_train.shape[2],rgersh_train.shape[3])
num_classes = classes
model3 = tf.keras.models.Sequential()
model3.add(tf.keras.layers.Conv2D(filters= 32, kernel_size=(1,3), activation='relu',padding='same',input_shape= input_shape))
model3.add(tf.keras.layers.AveragePooling2D(pool_size=(1, 2),strides=None,padding='valid'))
model3.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(1,3),padding='same',activation='relu'))
model3.add(tf.keras.layers.AveragePooling2D(pool_size=(1, 2),strides=None,padding='valid'))

model3.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(1,3),padding='same',activation='relu'))
model3.add(tf.keras.layers.AveragePooling2D(pool_size=(1, 2),strides=None,padding='valid'))

model3.add(tf.keras.layers.Flatten())
model3.add(tf.keras.layers.Dense(512, activation='relu'))
model3.add(tf.keras.layers.Dropout(0.1))
model3.add(tf.keras.layers.Dense(512, activation='relu'))
model3.add(tf.keras.layers.Dense(num_classes, activation='softmax'))


2023-07-25 16:34:46.055833: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/18.08.9/lib64/slurm:/cm/shared/apps/slurm/18.08.9/lib64
2023-07-25 16:34:46.055933: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-07-25 16:34:46.055967: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c0181): /proc/driver/nvidia/version does not exist
2023-07-25 16:34:46.057030: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow

In [61]:
model3.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 2, 784, 32)        128       
                                                                 
 average_pooling2d (AverageP  (None, 2, 392, 32)       0         
 ooling2D)                                                       
                                                                 
 conv2d_1 (Conv2D)           (None, 2, 392, 32)        3104      
                                                                 
 average_pooling2d_1 (Averag  (None, 2, 196, 32)       0         
 ePooling2D)                                                     
                                                                 
 conv2d_2 (Conv2D)           (None, 2, 196, 32)        3104      
                                                                 
 average_pooling2d_2 (Averag  (None, 2, 98, 32)        0

In [62]:
model3.compile(loss='SparseCategoricalCrossentropy', optimizer='Adam', metrics=['acc'])


In [63]:
history_log=model3.fit(rgersh_train, reg_train_label, epochs=10,verbose=1,validation_data=(rgersh_val, reg_val_label))


Epoch 1/10
3525/3525 [==============================] - 38s 10ms/step - loss: 0.8936 - acc: 0.7180 - val_loss: 0.5889 - val_acc: 0.7989
Epoch 2/10
3525/3525 [==============================] - 36s 10ms/step - loss: 0.5463 - acc: 0.8142 - val_loss: 0.5085 - val_acc: 0.8262
Epoch 3/10
3525/3525 [==============================] - 35s 10ms/step - loss: 0.4377 - acc: 0.8452 - val_loss: 0.5082 - val_acc: 0.8314
Epoch 4/10
3525/3525 [==============================] - 35s 10ms/step - loss: 0.3766 - acc: 0.8630 - val_loss: 0.4819 - val_acc: 0.8409
Epoch 5/10
3525/3525 [==============================] - 35s 10ms/step - loss: 0.3339 - acc: 0.8757 - val_loss: 0.4972 - val_acc: 0.8402
Epoch 6/10
3525/3525 [==============================] - 36s 10ms/step - loss: 0.2934 - acc: 0.8886 - val_loss: 0.5018 - val_acc: 0.8424
Epoch 7/10
3525/3525 [==============================] - 35s 10ms/step - loss: 0.2626 - acc: 0.8972 - val_loss: 0.5339 - val_acc: 0.8383
Epoch 8/10
3525/3525 [==========================

In [64]:
loss, accuracy = model3.evaluate(rgersh_test, reg_test_label)
print(f' Model loss on the test set: {loss}')
print(f' Model accuracy on the test set: {100*accuracy}')

294/294 [==============================] - 1s 3ms/step - loss: 0.5832 - acc: 0.8428
 Model loss on the test set: 0.5831887125968933
 Model accuracy on the test set: 84.27659869194031


In [65]:
predictions = model3.predict(rgersh_test)
pred_arg = np.argmax(predictions, axis=1)

294/294 [==============================] - 1s 3ms/step


In [66]:
from sklearn.metrics import confusion_matrix
cnf_matrix=confusion_matrix(reg_test_label,pred_arg)
print("cnf_matrix_2.0_70")
print("")
print(cnf_matrix)

cnf_matrix_2.0_70

[[ 75   0   0 ...   0   0   0]
 [  0 119   1 ...   2   1   0]
 [  0   0 171 ...   1   0   0]
 ...
 [  0   0   1 ... 102   0   0]
 [  0   0   0 ...   0 188   1]
 [  0   0   0 ...   0   2 172]]


In [67]:
from sklearn.metrics import accuracy_score, recall_score,precision_score,roc_auc_score,roc_curve,f1_score


In [68]:
print(accuracy_score(reg_test_label, pred_arg)*100)
print(f1_score(reg_test_label,pred_arg,average='macro')*100)
print(recall_score(reg_test_label, pred_arg, average="weighted")*100)
print(precision_score(reg_test_label, pred_arg, average="weighted")*100)

84.27659574468085
84.07308941915856
84.27659574468085
84.48055925487617
