In [1]:
import numpy as np
import matplotlib.pyplot as plt
from image_graph_util import img_conversion_v7
from sklearn.preprocessing import MinMaxScaler
import os
import glob
import tensorflow as tf
import tensorflow_datasets as tfds
from sklearn.model_selection import train_test_split
from emnist import extract_training_samples,extract_test_samples
from emnist import list_datasets
from sklearn.utils import shuffle

2023-07-09 12:37:22.715310: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-09 12:37:24.975005: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-09 12:37:26.436978: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/18.08.9/lib64/slurm:/cm/shared/apps/slurm/18.08.9/lib64
2023-

In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)


In [3]:
img=img_conversion_v7.image_convert()

patch=4


In [4]:
print(list_datasets())

['balanced', 'byclass', 'bymerge', 'digits', 'letters', 'mnist']


In [5]:
train_images,train_labels=extract_training_samples('balanced')

In [6]:
test_images, test_labels = extract_test_samples('balanced')

In [7]:
#normalization of train dataset
ftrain_images = np.float16(np.array(train_images)/255)
train_labels = np.float16(np.array(train_labels))

In [8]:
#normalization of test dataset
ftest_images = np.float16(np.array(test_images)/255)
test_labels = np.float16(np.array(test_labels))

In [9]:
print(ftrain_images.shape)
print(ftest_images.shape)

(112800, 28, 28)
(18800, 28, 28)


In [10]:
# making 28,28,1
rtrain_images=ftrain_images.reshape(ftrain_images.shape[0],ftrain_images.shape[1],ftrain_images.shape[2],1)
rtest_images=ftest_images.reshape(ftest_images.shape[0],ftest_images.shape[1],ftest_images.shape[2],1)

In [11]:
print(rtrain_images.shape)
print(rtest_images.shape)

(112800, 28, 28, 1)
(18800, 28, 28, 1)


In [12]:
reg_val,reg_test,reg_val_label,reg_test_label=train_test_split(rtest_images,test_labels,test_size=0.50,random_state=42)


In [13]:
reg_train=rtrain_images
reg_train_label=train_labels


In [14]:
print(reg_train.shape)
print(reg_val.shape)
print(reg_test.shape)
print(reg_train_label.shape)
print(reg_val_label.shape)
print(reg_test_label.shape)


(112800, 28, 28, 1)
(9400, 28, 28, 1)
(9400, 28, 28, 1)
(112800,)
(9400,)
(9400,)


In [15]:
reg_train_patch=img.to_patcharray(reg_train,patch_size=(patch,patch))
reg_val_patch=img.to_patcharray(reg_val,patch_size=(patch,patch))
reg_test_patch=img.to_patcharray(reg_test,patch_size=(patch,patch))

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



####  Patch size

In [16]:
print(reg_train_patch.shape)
print(reg_val_patch.shape)
print(reg_test_patch.shape)

In [17]:
from collections import Counter
#print((Counter(y_val)))
print(np.sort(list(Counter(reg_train_label).keys())))
classes=len(np.sort(list(Counter(reg_train_label).keys())))

# Laplacian image analysis

In [18]:
import networkx as nx


def compute_grid_lap_channel(df_in): #compute_grid_lap_channel
    g = nx.generators.lattice.grid_2d_graph(patch,patch, periodic=False)
    adj_ary=nx.adjacency_matrix(g).toarray()

    edge=np.array(np.where(adj_ary==1))
    ed0=edge[0]
    ed1=edge[1]

    no_img,no_ch, no_patch,patch_x,patch_y=df_in.shape
    temp=[]
    for i in range(no_img):
        i_ary = np.eye(patch_x*patch_y)
        i_ary4d=i_ary[np.newaxis,np.newaxis,:,:]
        weighted_adj=np.zeros((no_ch, no_patch,patch_x*patch_y,patch_x*patch_y))
        df=df_in[i].reshape(no_ch,no_patch,-1)
        pixel1=df[:,:,ed0]
        pixel2=df[:,:,ed1]  
        edu_distance=np.sqrt((pixel1-pixel2)**2)+ 10**(-8)
        weighted_adj[:,:,ed0,ed1]=edu_distance
        sum_r=np.sum(weighted_adj,axis=2)
        temp_adj=sum_r[:,:,:,np.newaxis]
        deg=temp_adj*i_ary4d
        L=deg-weighted_adj
        temp.append(L)
    return temp



In [19]:
from multiprocessing import Pool
import multiprocessing



num_cores = multiprocessing.cpu_count()
print("Number of CPU cores:", num_cores)


In [20]:
train_patch1=np.array_split(reg_train_patch[:], num_cores)
val_patch1=np.array_split(reg_val_patch[:], num_cores)
test_patch1=np.array_split(reg_test_patch[:], num_cores)

In [21]:
print(len(train_patch1))
print(len(val_patch1))
print(len(test_patch1))

In [22]:
with Pool(processes=num_cores) as pool:
        # Define a list of numbers
    train_p = train_patch1
    
        # Apply the square function to each number using the pool
    g_train=pool.map(compute_grid_lap_channel,train_p)
pool.close()


    
        #results = pool.map(calculate_visibility, numbers)


In [23]:
temp1=[]
for submatrix in g_train:
    temp1.extend(submatrix)


In [24]:
gersh_train= np.array([np.asarray(submatrix) for submatrix in temp1])


In [25]:
print("d")

d


In [26]:
with Pool(processes=num_cores) as pool1:
        # Define a list of numbers
    val_p = val_patch1
    
        # Apply the square function to each number using the pool
    g_val=pool1.map(compute_grid_lap_channel,val_patch1)    
pool1.close()



In [27]:
temp2=[]
for submatrix in g_val:
    temp2.extend(submatrix)


In [28]:
gersh_val= np.array([np.asarray(submatrix) for submatrix in temp2])


In [29]:
print("d")

d


In [30]:
with Pool(processes=num_cores) as pool2:
        # Define a list of numbers
    test_p = test_patch1
    
        # Apply the square function to each number using the pool
    g_test=pool2.map(compute_grid_lap_channel,test_patch1) 
pool2.close()


In [31]:
temp3=[]
for submatrix in g_test:
    temp3.extend(submatrix)


In [32]:
gersh_test= np.array([np.asarray(submatrix) for submatrix in temp3])


gersh_train=np.array(img1.to_gridlaparray(train_patch))
gersh_val=np.array(img1.to_gridlaparray(val_patch))
gersh_test=np.array(img1.to_gridlaparray(test_patch))

In [33]:
print(gersh_train.shape)
print(gersh_val.shape)
print(gersh_test.shape)

(112800, 1, 49, 16, 16)
(9400, 1, 49, 16, 16)
(9400, 1, 49, 16, 16)


In [34]:
lap_train=gersh_train
lap_val=gersh_val
lap_test=gersh_test

In [35]:
print(lap_train.shape)
print(lap_val.shape)
print(lap_test.shape)

(112800, 1, 49, 16, 16)
(9400, 1, 49, 16, 16)
(9400, 1, 49, 16, 16)


In [36]:
rlap_train=np.moveaxis(lap_train,1,-1)
rlap_val=np.moveaxis(lap_val,1,-1)
rlap_test=np.moveaxis(lap_test,1,-1)



In [37]:
rlap_train=rlap_train.reshape(rlap_train.shape[0],rlap_train.shape[1]*rlap_train.shape[2],rlap_train.shape[3],rlap_train.shape[4])
rlap_val=rlap_val.reshape(rlap_val.shape[0],rlap_val.shape[1]*rlap_val.shape[2],rlap_val.shape[3],rlap_val.shape[4])
rlap_test=rlap_test.reshape(rlap_test.shape[0],rlap_test.shape[1]*rlap_test.shape[2],rlap_test.shape[3],rlap_test.shape[4])

In [38]:
print(rlap_train.shape)
print(rlap_train.shape)
print(rlap_train.shape)

(112800, 784, 16, 1)
(112800, 784, 16, 1)
(112800, 784, 16, 1)


In [39]:
rrlap_train=rlap_train.reshape(rlap_train.shape[0],-1)
rrlap_val=rlap_val.reshape(rlap_val.shape[0],-1)
rrlap_test=rlap_test.reshape(rlap_test.shape[0],-1)

In [40]:
print(rrlap_train.shape)
print(rrlap_train.shape)
print(rrlap_train.shape)

(112800, 12544)
(112800, 12544)
(112800, 12544)


In [41]:
L= np.concatenate((rrlap_train,rrlap_val,rrlap_test), axis=0)


In [42]:
print(L.shape)

(131600, 12544)


In [43]:
import numpy as np
from sklearn.manifold import SpectralEmbedding
import time
# Assuming you have your flattened Laplacian matrix stored in a variable called flattened_laplacian_matrix
# Assuming the original shape of the Laplacian matrix is (6000, 6000)

#Reshape the flattened Laplacian matrix back to its original shape
random_matrix = L
subset_size = 12544  # Define the size of the subset
subset_matrix = random_matrix[:12544, :]

graph_laplacian= .5*(subset_matrix + subset_matrix.T)
start=time.time()
# Perform eigen-decomposition on the Laplacian matrix
eigenvalues, eigenvectors = np.linalg.eigh(graph_laplacian)

# Sort eigenvalues and eigenvectors in ascending order
sorted_indices = np.argsort(eigenvalues)
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

# Choose the desired number of dimensions for the embedding
n_dimensions = 1568

# Extract the first 'n_dimensions' eigenvectors
embedding = sorted_eigenvectors[:, 1:n_dimensions+1]

# Normalize the embedding
embedding = embedding / np.linalg.norm(embedding, axis=1, keepdims=True)
end=time.time()
print("--- %s seconds ---" % (end - start))

# Alternatively, you can use the SpectralEmbedding class from Scikit-Learn
# spectral_embedder = SpectralEmbedding(n_components=n_dimensions, affinity='precomputed')
# embedding = spectral_embedder.fit_transform(laplacian_matrix)
#embedding = embedding.numpy()

# The 'embedding' variable now contains the low-dimensional representation of your data using Laplacian Eigenmap

# Use the embedding for further analysis or visualization


--- 54.39382553100586 seconds ---


In [44]:
embedding.shape

(12544, 1568)

In [45]:
transformed_data  = np.dot(random_matrix[:], embedding)


In [46]:
transformed_data .shape

(131600, 1568)

In [47]:
x_train=transformed_data[:rlap_train.shape[0]]
x_val=transformed_data[rlap_train.shape[0]:(rlap_train.shape[0]+rlap_val.shape[0])]
x_test=transformed_data[(rlap_train.shape[0]+rlap_val.shape[0]):]



In [48]:
print(x_train.shape)
print(x_val.shape)
print(x_test.shape)

(112800, 1568)
(9400, 1568)
(9400, 1568)


In [49]:
input_shape = (x_train.shape[1],1)
num_classes = classes
model2 = tf.keras.models.Sequential()
model2.add(tf.keras.layers.Conv1D(filters= 32, kernel_size=3, activation='relu',padding='same',input_shape= input_shape))
model2.add(tf.keras.layers.AveragePooling1D())
model2.add(tf.keras.layers.Conv1D(filters=32, kernel_size=3,padding='same',activation='relu'))
model2.add(tf.keras.layers.AveragePooling1D())
model2.add(tf.keras.layers.Conv1D(filters=32, kernel_size=3,padding='same',activation='relu'))
model2.add(tf.keras.layers.AveragePooling1D())
model2.add(tf.keras.layers.Flatten())
model2.add(tf.keras.layers.Dense(512, activation='relu'))
model2.add(tf.keras.layers.Dropout(0.1))
model2.add(tf.keras.layers.Dense(512, activation='relu'))
model2.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

model2.compile(loss='SparseCategoricalCrossentropy', optimizer='Adam', metrics=['acc'])


2023-07-09 12:40:44.636261: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/18.08.9/lib64/slurm:/cm/shared/apps/slurm/18.08.9/lib64
2023-07-09 12:40:44.716532: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-07-09 12:40:44.716623: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c0152): /proc/driver/nvidia/version does not exist
2023-07-09 12:40:44.798842: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow

In [50]:
model2.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 1568, 32)          128       
                                                                 
 average_pooling1d (AverageP  (None, 784, 32)          0         
 ooling1D)                                                       
                                                                 
 conv1d_1 (Conv1D)           (None, 784, 32)           3104      
                                                                 
 average_pooling1d_1 (Averag  (None, 392, 32)          0         
 ePooling1D)                                                     
                                                                 
 conv1d_2 (Conv1D)           (None, 392, 32)           3104      
                                                                 
 average_pooling1d_2 (Averag  (None, 196, 32)          0

In [51]:
history_log=model2.fit(x_train, reg_train_label, epochs=10,verbose=1,validation_data=(x_val, reg_val_label))


Epoch 1/10
3525/3525 [==============================] - 39s 10ms/step - loss: 1.4427 - acc: 0.5655 - val_loss: 0.8537 - val_acc: 0.7290
Epoch 2/10
3525/3525 [==============================] - 36s 10ms/step - loss: 0.7476 - acc: 0.7512 - val_loss: 0.7609 - val_acc: 0.7543
Epoch 3/10
3525/3525 [==============================] - 37s 10ms/step - loss: 0.6024 - acc: 0.7940 - val_loss: 0.7038 - val_acc: 0.7779
Epoch 4/10
3525/3525 [==============================] - 37s 10ms/step - loss: 0.5114 - acc: 0.8200 - val_loss: 0.6975 - val_acc: 0.7822
Epoch 5/10
3525/3525 [==============================] - 37s 10ms/step - loss: 0.4409 - acc: 0.8421 - val_loss: 0.7421 - val_acc: 0.7786
Epoch 6/10
3525/3525 [==============================] - 37s 11ms/step - loss: 0.3909 - acc: 0.8564 - val_loss: 0.7745 - val_acc: 0.7765
Epoch 7/10
3525/3525 [==============================] - 37s 10ms/step - loss: 0.3483 - acc: 0.8696 - val_loss: 0.8012 - val_acc: 0.7748
Epoch 8/10
3525/3525 [==========================

In [52]:
loss, accuracy = model2.evaluate(x_test, reg_test_label)
print(f' Model loss on the test set: {loss}')
print(f' Model accuracy on the test set: {100*accuracy}')

294/294 [==============================] - 1s 3ms/step - loss: 0.8926 - acc: 0.7633
 Model loss on the test set: 0.8925580978393555
 Model accuracy on the test set: 76.32978558540344


In [53]:
predictions = model2.predict(x_test)
pred_arg = np.argmax(predictions, axis=1)

294/294 [==============================] - 1s 3ms/step


In [54]:
from sklearn.metrics import confusion_matrix
cnf_matrix=confusion_matrix(reg_test_label,pred_arg)
print("cnf_matrix_2.0_70")
print("")
print(cnf_matrix)

cnf_matrix_2.0_70

[[ 87   0   0 ...   0   0   0]
 [  0 113   1 ...   1   2   0]
 [  0   0 143 ...   2   0   0]
 ...
 [  1   0   5 ...  94   0   1]
 [  0   1   0 ...   0 189   1]
 [  0   1   0 ...   1   1 161]]


In [55]:
from sklearn.metrics import accuracy_score, recall_score,precision_score,roc_auc_score,roc_curve,f1_score


In [56]:
print(accuracy_score(reg_test_label, pred_arg))
print(f1_score(reg_test_label,pred_arg,average='macro'))
print(recall_score(reg_test_label, pred_arg, average="weighted"))
print(precision_score(reg_test_label, pred_arg, average="weighted"))

0.7632978723404256
0.7629352451861243
0.7632978723404256
0.7683625924014279
