In [23]:
import numpy as np
import matplotlib.pyplot as plt
from image_graph_util import img_conversion_v7
from sklearn.preprocessing import MinMaxScaler
import os
import glob
import tensorflow as tf
import tensorflow_datasets as tfds
from sklearn.model_selection import train_test_split
from emnist import extract_training_samples,extract_test_samples
from emnist import list_datasets
from sklearn.utils import shuffle

In [24]:
img=img_conversion_v7.image_convert()

patch=14


In [25]:
print(list_datasets())

['balanced', 'byclass', 'bymerge', 'digits', 'letters', 'mnist']


In [26]:
train_images,train_labels=extract_training_samples('mnist')

In [27]:
test_images, test_labels = extract_test_samples('mnist')

In [28]:
#normalization of train dataset
ftrain_images = np.float16(np.array(train_images)/255)
train_labels = np.float16(np.array(train_labels))

In [29]:
#normalization of test dataset
ftest_images = np.float16(np.array(test_images)/255)
test_labels = np.float16(np.array(test_labels))

In [30]:
print(ftrain_images.shape)
print(ftest_images.shape)

(60000, 28, 28)
(10000, 28, 28)


In [31]:
# making 28,28,1
rtrain_images=ftrain_images.reshape(ftrain_images.shape[0],ftrain_images.shape[1],ftrain_images.shape[2],1)
rtest_images=ftest_images.reshape(ftest_images.shape[0],ftest_images.shape[1],ftest_images.shape[2],1)

In [32]:
print(rtrain_images.shape)
print(rtest_images.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [33]:
reg_val,reg_test,reg_val_label,reg_test_label=train_test_split(rtest_images,test_labels,test_size=0.50,random_state=42)


In [34]:
reg_train=rtrain_images
reg_train_label=train_labels


In [35]:
print(reg_train.shape)
print(reg_val.shape)
print(reg_test.shape)
print(reg_train_label.shape)
print(reg_val_label.shape)
print(reg_test_label.shape)


(60000, 28, 28, 1)
(5000, 28, 28, 1)
(5000, 28, 28, 1)
(60000,)
(5000,)
(5000,)


In [36]:
reg_train_patch=img.to_patcharray(reg_train,patch_size=(patch,patch))
reg_val_patch=img.to_patcharray(reg_val,patch_size=(patch,patch))
reg_test_patch=img.to_patcharray(reg_test,patch_size=(patch,patch))

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



####  Patch size

In [37]:
print(reg_train_patch.shape)
print(reg_val_patch.shape)
print(reg_test_patch.shape)

(60000, 1, 4, 14, 14)
(5000, 1, 4, 14, 14)
(5000, 1, 4, 14, 14)


In [38]:
from collections import Counter
#print((Counter(y_val)))
print(np.sort(list(Counter(reg_train_label).keys())))
classes=len(np.sort(list(Counter(reg_train_label).keys())))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# Gershgorien image analysis

In [39]:
import networkx as nx



def compute_gridlap_to_gersh(df_in):
    g = nx.generators.lattice.grid_2d_graph(patch,patch, periodic=False)
    adj_ary=nx.adjacency_matrix(g).toarray()

    gersh_c=np.tile(np.sum(adj_ary,axis=0),(reg_train_patch.shape[1],reg_train_patch.shape[2]))

    edge=np.array(np.where(adj_ary==1))
    ed0=edge[0]
    ed1=edge[1]
    
    no_img,no_ch, no_patch,patch_x,patch_y=df_in.shape
    temp=[]
    for i in range(no_img):
        i_ary = np.eye(patch_x*patch_y)
        i_ary4d=i_ary[np.newaxis,np.newaxis,:,:]
        weighted_adj=np.zeros((no_ch, no_patch,patch_x*patch_y,patch_x*patch_y))
        df=df_in[i].reshape(no_ch,no_patch,-1)
        pixel1=df[:,:,ed0]
        pixel2=df[:,:,ed1]  
        edu_distance=np.sqrt((pixel1-pixel2)**2)+ 10**(-8)
        weighted_adj[:,:,ed0,ed1]=edu_distance
        sum_r=np.sum(weighted_adj,axis=2)
        gersh_r=sum_r.reshape(no_ch,-1)
        gersh_total=np.vstack((gersh_r[0],gersh_c[0])) #,gersh_r[1],gersh_c[1],gersh_r[2],gersh_c[2]
        gersh_total=gersh_total.reshape(no_ch,2,gersh_c.shape[-1])
        temp.append(gersh_total)
    return temp



In [40]:
from multiprocessing import Pool
import multiprocessing



num_cores = multiprocessing.cpu_count()
print("Number of CPU cores:", num_cores)


Number of CPU cores: 48


In [41]:
train_patch1=np.array_split(reg_train_patch[:], num_cores)
val_patch1=np.array_split(reg_val_patch[:], num_cores)
test_patch1=np.array_split(reg_test_patch[:], num_cores)

In [42]:
print(len(train_patch1))
print(len(val_patch1))
print(len(test_patch1))

48
48
48


In [43]:
with Pool(processes=num_cores) as pool:
        # Define a list of numbers
    train_p = train_patch1
    
        # Apply the square function to each number using the pool
    g_train=pool.map(compute_gridlap_to_gersh,train_p)
pool.close()


    
        #results = pool.map(calculate_visibility, numbers)


In [44]:
temp1=[]
for submatrix in g_train:
    temp1.extend(submatrix)


In [45]:
gersh_train= np.array([np.asarray(submatrix) for submatrix in temp1])


In [46]:
print("d")

d


In [47]:
with Pool(processes=num_cores) as pool1:
        # Define a list of numbers
    val_p = val_patch1
    
        # Apply the square function to each number using the pool
    g_val=pool1.map(compute_gridlap_to_gersh,val_patch1)    
pool1.close()



In [48]:
temp2=[]
for submatrix in g_val:
    temp2.extend(submatrix)


In [49]:
gersh_val= np.array([np.asarray(submatrix) for submatrix in temp2])


In [50]:
print("d")

d


In [51]:
with Pool(processes=num_cores) as pool2:
        # Define a list of numbers
    test_p = test_patch1
    
        # Apply the square function to each number using the pool
    g_test=pool2.map(compute_gridlap_to_gersh,test_patch1) 
pool2.close()


In [52]:
temp3=[]
for submatrix in g_test:
    temp3.extend(submatrix)


In [53]:
gersh_test= np.array([np.asarray(submatrix) for submatrix in temp3])


In [54]:
print(gersh_train.shape)
print(gersh_val.shape)
print(gersh_test.shape)

(60000, 1, 2, 784)
(5000, 1, 2, 784)
(5000, 1, 2, 784)


In [55]:
rgersh_train=np.moveaxis(gersh_train,1,-1)
rgersh_val=np.moveaxis(gersh_val,1,-1)
rgersh_test=np.moveaxis(gersh_test,1,-1)


In [56]:
print(rgersh_train.shape)
print(rgersh_train.shape)
print(rgersh_train.shape)

(60000, 2, 784, 1)
(60000, 2, 784, 1)
(60000, 2, 784, 1)


# Gershgorien 2D CNN

In [57]:
input_shape = (rgersh_train.shape[1],rgersh_train.shape[2],rgersh_train.shape[3])
num_classes = classes
model3 = tf.keras.models.Sequential()
model3.add(tf.keras.layers.Conv2D(filters= 32, kernel_size=(1,3), activation='relu',padding='same',input_shape= input_shape))
model3.add(tf.keras.layers.AveragePooling2D(pool_size=(1, 2),strides=None,padding='valid'))
model3.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(1,3),padding='same',activation='relu'))
model3.add(tf.keras.layers.AveragePooling2D(pool_size=(1, 2),strides=None,padding='valid'))

model3.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(1,3),padding='same',activation='relu'))
model3.add(tf.keras.layers.AveragePooling2D(pool_size=(1, 2),strides=None,padding='valid'))

model3.add(tf.keras.layers.Flatten())
model3.add(tf.keras.layers.Dense(512, activation='relu'))
model3.add(tf.keras.layers.Dropout(0.1))
model3.add(tf.keras.layers.Dense(512, activation='relu'))
model3.add(tf.keras.layers.Dense(num_classes, activation='softmax'))


2023-07-07 19:03:02.096884: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/18.08.9/lib64/slurm:/cm/shared/apps/slurm/18.08.9/lib64
2023-07-07 19:03:02.096928: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-07-07 19:03:02.096968: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c0172): /proc/driver/nvidia/version does not exist
2023-07-07 19:03:02.098041: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow

In [58]:
model3.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 2, 784, 32)        128       
                                                                 
 average_pooling2d (AverageP  (None, 2, 392, 32)       0         
 ooling2D)                                                       
                                                                 
 conv2d_1 (Conv2D)           (None, 2, 392, 32)        3104      
                                                                 
 average_pooling2d_1 (Averag  (None, 2, 196, 32)       0         
 ePooling2D)                                                     
                                                                 
 conv2d_2 (Conv2D)           (None, 2, 196, 32)        3104      
                                                                 
 average_pooling2d_2 (Averag  (None, 2, 98, 32)        0

In [59]:
model3.compile(loss='SparseCategoricalCrossentropy', optimizer='Adam', metrics=['acc'])


In [60]:
history_log=model3.fit(rgersh_train, reg_train_label, epochs=10,verbose=1,validation_data=(rgersh_val, reg_val_label))


Epoch 1/10
1875/1875 [==============================] - 20s 10ms/step - loss: 0.2859 - acc: 0.9075 - val_loss: 0.1222 - val_acc: 0.9640
Epoch 2/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.1123 - acc: 0.9649 - val_loss: 0.0910 - val_acc: 0.9730
Epoch 3/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.0803 - acc: 0.9754 - val_loss: 0.0750 - val_acc: 0.9770
Epoch 4/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.0620 - acc: 0.9802 - val_loss: 0.0669 - val_acc: 0.9804
Epoch 5/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.0456 - acc: 0.9851 - val_loss: 0.0717 - val_acc: 0.9786
Epoch 6/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.0348 - acc: 0.9887 - val_loss: 0.0746 - val_acc: 0.9798
Epoch 7/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.0297 - acc: 0.9901 - val_loss: 0.0758 - val_acc: 0.9794
Epoch 8/10
1875/1875 [==========================

In [61]:
loss, accuracy = model3.evaluate(rgersh_test, reg_test_label)
print(f' Model loss on the test set: {loss}')
print(f' Model accuracy on the test set: {100*accuracy}')

157/157 [==============================] - 0s 3ms/step - loss: 0.0826 - acc: 0.9810
 Model loss on the test set: 0.0825885534286499
 Model accuracy on the test set: 98.1000006198883


In [62]:
predictions = model3.predict(rgersh_test)
pred_arg = np.argmax(predictions, axis=1)

157/157 [==============================] - 0s 2ms/step


In [63]:
from sklearn.metrics import confusion_matrix
cnf_matrix=confusion_matrix(reg_test_label,pred_arg)
print("cnf_matrix_2.0_70")
print("")
print(cnf_matrix)

cnf_matrix_2.0_70

[[479   2   1   1   1   0   1   0   2   0]
 [  0 525   2   0   1   0   1   0   0   0]
 [  1   0 498   4   0   1   0   2   1   0]
 [  2   1   6 492   0   2   0   1   2   0]
 [  0   0   6   0 498   0   0   2   0   6]
 [  0   0   0   4   0 466   0   1   2   0]
 [  1   0   0   0   0   2 483   0   0   0]
 [  0   1   3   1   3   0   0 492   1   1]
 [  1   0   4   3   1   4   0   2 470   1]
 [  0   0   1   1   3   0   0   3   2 502]]


In [64]:
from sklearn.metrics import accuracy_score, recall_score,precision_score,roc_auc_score,roc_curve,f1_score


In [65]:
print(accuracy_score(reg_test_label, pred_arg)*100)
print(f1_score(reg_test_label,pred_arg,average='macro')*100)
print(recall_score(reg_test_label, pred_arg, average="weighted")*100)
print(precision_score(reg_test_label, pred_arg, average="weighted")*100)

98.1
98.1023263831793
98.1
98.10795120716519
