In [57]:
import numpy as np
import matplotlib.pyplot as plt
from image_graph_util import img_conversion_v7
from sklearn.preprocessing import MinMaxScaler
import os
import glob
import tensorflow as tf
import tensorflow_datasets as tfds
from sklearn.model_selection import train_test_split
from emnist import extract_training_samples,extract_test_samples
from emnist import list_datasets
from sklearn.utils import shuffle

In [58]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)


In [59]:
img=img_conversion_v7.image_convert()

patch=4


In [60]:
print(list_datasets())

['balanced', 'byclass', 'bymerge', 'digits', 'letters', 'mnist']


In [61]:
train_images,train_labels=extract_training_samples('mnist')

In [62]:
test_images, test_labels = extract_test_samples('mnist')

In [63]:
#normalization of train dataset
ftrain_images = np.float16(np.array(train_images)/255)
train_labels = np.float16(np.array(train_labels))

In [64]:
#normalization of test dataset
ftest_images = np.float16(np.array(test_images)/255)
test_labels = np.float16(np.array(test_labels))

In [65]:
print(ftrain_images.shape)
print(ftest_images.shape)

(60000, 28, 28)
(10000, 28, 28)


In [66]:
# making 28,28,1
rtrain_images=ftrain_images.reshape(ftrain_images.shape[0],ftrain_images.shape[1],ftrain_images.shape[2],1)
rtest_images=ftest_images.reshape(ftest_images.shape[0],ftest_images.shape[1],ftest_images.shape[2],1)

In [67]:
print(rtrain_images.shape)
print(rtest_images.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [68]:
reg_val,reg_test,reg_val_label,reg_test_label=train_test_split(rtest_images,test_labels,test_size=0.50,random_state=42)


In [69]:
reg_train=rtrain_images
reg_train_label=train_labels


In [70]:
print(reg_train.shape)
print(reg_val.shape)
print(reg_test.shape)
print(reg_train_label.shape)
print(reg_val_label.shape)
print(reg_test_label.shape)


(60000, 28, 28, 1)
(5000, 28, 28, 1)
(5000, 28, 28, 1)
(60000,)
(5000,)
(5000,)


In [71]:
reg_train_patch=img.to_patcharray(reg_train,patch_size=(patch,patch))
reg_val_patch=img.to_patcharray(reg_val,patch_size=(patch,patch))
reg_test_patch=img.to_patcharray(reg_test,patch_size=(patch,patch))

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



####  Patch size

In [72]:
print(reg_train_patch.shape)
print(reg_val_patch.shape)
print(reg_test_patch.shape)

In [73]:
from collections import Counter
#print((Counter(y_val)))
print(np.sort(list(Counter(reg_train_label).keys())))
classes=len(np.sort(list(Counter(reg_train_label).keys())))

# Laplacian image analysis

In [74]:
import networkx as nx


def compute_laplacian_channel(df_in): #compute_laplacian_channel
    adj_ary=np.ones(reg_train_patch.shape[-2]*reg_train_patch.shape[-1])-np.eye(reg_train_patch.shape[-2]*reg_train_patch.shape[-1])

    edge=np.array(np.where(adj_ary==1))
    ed0=edge[0]
    ed1=edge[1]

    no_img,no_ch, no_patch,patch_x,patch_y=df_in.shape
    temp=[]
    for i in range(no_img):
        i_ary = np.eye(patch_x*patch_y)
        i_ary4d=i_ary[np.newaxis,np.newaxis,:,:]
        weighted_adj=np.zeros((no_ch, no_patch,patch_x*patch_y,patch_x*patch_y))
        df=df_in[i].reshape(no_ch,no_patch,-1)
        pixel1=df[:,:,ed0]
        pixel2=df[:,:,ed1]  
        edu_distance=np.sqrt((pixel1-pixel2)**2)+ 10**(-8)
        weighted_adj[:,:,ed0,ed1]=edu_distance
        sum_r=np.sum(weighted_adj,axis=2)
        temp_adj=sum_r[:,:,:,np.newaxis]
        deg=temp_adj*i_ary4d
        L=deg-weighted_adj
        temp.append(L)
    return temp



In [75]:
from multiprocessing import Pool
import multiprocessing



num_cores = multiprocessing.cpu_count()
print("Number of CPU cores:", num_cores)


In [76]:
train_patch1=np.array_split(reg_train_patch[:], num_cores)
val_patch1=np.array_split(reg_val_patch[:], num_cores)
test_patch1=np.array_split(reg_test_patch[:], num_cores)

In [77]:
print(len(train_patch1))
print(len(val_patch1))
print(len(test_patch1))

In [78]:
with Pool(processes=num_cores) as pool:
        # Define a list of numbers
    train_p = train_patch1
    
        # Apply the square function to each number using the pool
    g_train=pool.map(compute_laplacian_channel,train_p)
pool.close()


    
        #results = pool.map(calculate_visibility, numbers)


In [79]:
temp1=[]
for submatrix in g_train:
    temp1.extend(submatrix)


In [80]:
gersh_train= np.array([np.asarray(submatrix) for submatrix in temp1])


In [81]:
print("d")

d


In [82]:
with Pool(processes=num_cores) as pool1:
        # Define a list of numbers
    val_p = val_patch1
    
        # Apply the square function to each number using the pool
    g_val=pool1.map(compute_laplacian_channel,val_patch1)    
pool1.close()



In [83]:
temp2=[]
for submatrix in g_val:
    temp2.extend(submatrix)


In [84]:
gersh_val= np.array([np.asarray(submatrix) for submatrix in temp2])


In [85]:
print("d")

d


In [86]:
with Pool(processes=num_cores) as pool2:
        # Define a list of numbers
    test_p = test_patch1
    
        # Apply the square function to each number using the pool
    g_test=pool2.map(compute_laplacian_channel,test_patch1) 
pool2.close()


In [87]:
temp3=[]
for submatrix in g_test:
    temp3.extend(submatrix)


In [88]:
gersh_test= np.array([np.asarray(submatrix) for submatrix in temp3])


gersh_train=np.array(img1.to_gridlaparray(train_patch))
gersh_val=np.array(img1.to_gridlaparray(val_patch))
gersh_test=np.array(img1.to_gridlaparray(test_patch))

In [89]:
print(gersh_train.shape)
print(gersh_val.shape)
print(gersh_test.shape)

(60000, 1, 49, 16, 16)
(5000, 1, 49, 16, 16)
(5000, 1, 49, 16, 16)


In [90]:
lap_train=gersh_train
lap_val=gersh_val
lap_test=gersh_test

In [91]:
print(lap_train.shape)
print(lap_val.shape)
print(lap_test.shape)

(60000, 1, 49, 16, 16)
(5000, 1, 49, 16, 16)
(5000, 1, 49, 16, 16)


In [92]:
rlap_train=np.moveaxis(lap_train,1,-1)
rlap_val=np.moveaxis(lap_val,1,-1)
rlap_test=np.moveaxis(lap_test,1,-1)



In [93]:
rlap_train=rlap_train.reshape(rlap_train.shape[0],rlap_train.shape[1]*rlap_train.shape[2],rlap_train.shape[3],rlap_train.shape[4])
rlap_val=rlap_val.reshape(rlap_val.shape[0],rlap_val.shape[1]*rlap_val.shape[2],rlap_val.shape[3],rlap_val.shape[4])
rlap_test=rlap_test.reshape(rlap_test.shape[0],rlap_test.shape[1]*rlap_test.shape[2],rlap_test.shape[3],rlap_test.shape[4])

In [94]:
print(rlap_train.shape)
print(rlap_train.shape)
print(rlap_train.shape)

(60000, 784, 16, 1)
(60000, 784, 16, 1)
(60000, 784, 16, 1)


In [95]:
rlap_train=rlap_train.reshape(rlap_train.shape[0],-1)
rlap_val=rlap_val.reshape(rlap_val.shape[0],-1)
rlap_test=rlap_test.reshape(rlap_test.shape[0],-1)

In [96]:
print(rlap_train.shape)
print(rlap_train.shape)
print(rlap_train.shape)

(60000, 12544)
(60000, 12544)
(60000, 12544)


In [97]:
L= np.concatenate((rlap_train,rlap_val,rlap_test), axis=0)


In [98]:
print(L.shape)

(70000, 12544)


In [99]:
import numpy as np
from sklearn.manifold import SpectralEmbedding
import time
# Assuming you have your flattened Laplacian matrix stored in a variable called flattened_laplacian_matrix
# Assuming the original shape of the Laplacian matrix is (6000, 6000)

#Reshape the flattened Laplacian matrix back to its original shape
random_matrix = L
subset_size = 12544  # Define the size of the subset
subset_matrix = random_matrix[:12544, :]

graph_laplacian= .5*(subset_matrix + subset_matrix.T)
start=time.time()
# Perform eigen-decomposition on the Laplacian matrix
eigenvalues, eigenvectors = np.linalg.eigh(graph_laplacian)

# Sort eigenvalues and eigenvectors in ascending order
sorted_indices = np.argsort(eigenvalues)
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

# Choose the desired number of dimensions for the embedding
n_dimensions = 1568

# Extract the first 'n_dimensions' eigenvectors
embedding = sorted_eigenvectors[:, 1:n_dimensions+1]

# Normalize the embedding
embedding = embedding / np.linalg.norm(embedding, axis=1, keepdims=True)
end=time.time()
print("--- %s seconds ---" % (end - start))

# Alternatively, you can use the SpectralEmbedding class from Scikit-Learn
# spectral_embedder = SpectralEmbedding(n_components=n_dimensions, affinity='precomputed')
# embedding = spectral_embedder.fit_transform(laplacian_matrix)
#embedding = embedding.numpy()

# The 'embedding' variable now contains the low-dimensional representation of your data using Laplacian Eigenmap

# Use the embedding for further analysis or visualization


--- 55.70160222053528 seconds ---


In [100]:
embedding.shape

(12544, 1568)

In [101]:
transformed_data  = np.dot(random_matrix[:], embedding)


In [102]:
transformed_data .shape

(70000, 1568)

In [103]:
x_train=transformed_data[:rlap_train.shape[0]]
x_val=transformed_data[rlap_train.shape[0]:(rlap_train.shape[0]+rlap_val.shape[0])]
x_test=transformed_data[(rlap_train.shape[0]+rlap_val.shape[0]):]



In [104]:
print(x_train.shape)
print(x_val.shape)
print(x_test.shape)

(60000, 1568)
(5000, 1568)
(5000, 1568)


In [105]:
input_shape = (x_train.shape[1],1)
num_classes = classes
model2 = tf.keras.models.Sequential()
model2.add(tf.keras.layers.Conv1D(filters= 32, kernel_size=3, activation='relu',padding='same',input_shape= input_shape))
model2.add(tf.keras.layers.AveragePooling1D())
model2.add(tf.keras.layers.Conv1D(filters=32, kernel_size=3,padding='same',activation='relu'))
model2.add(tf.keras.layers.AveragePooling1D())
model2.add(tf.keras.layers.Conv1D(filters=32, kernel_size=3,padding='same',activation='relu'))
model2.add(tf.keras.layers.AveragePooling1D())
model2.add(tf.keras.layers.Flatten())
model2.add(tf.keras.layers.Dense(512, activation='relu'))
model2.add(tf.keras.layers.Dropout(0.1))
model2.add(tf.keras.layers.Dense(512, activation='relu'))
model2.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

model2.compile(loss='SparseCategoricalCrossentropy', optimizer='Adam', metrics=['acc'])


In [106]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_3 (Conv1D)           (None, 1568, 32)          128       
                                                                 
 average_pooling1d_3 (Averag  (None, 784, 32)          0         
 ePooling1D)                                                     
                                                                 
 conv1d_4 (Conv1D)           (None, 784, 32)           3104      
                                                                 
 average_pooling1d_4 (Averag  (None, 392, 32)          0         
 ePooling1D)                                                     
                                                                 
 conv1d_5 (Conv1D)           (None, 392, 32)           3104      
                                                                 
 average_pooling1d_5 (Averag  (None, 196, 32)         

In [107]:
history_log=model2.fit(x_train, reg_train_label, epochs=10,verbose=1,validation_data=(x_val, reg_val_label))


Epoch 1/10
1875/1875 [==============================] - 20s 10ms/step - loss: 0.3573 - acc: 0.8849 - val_loss: 0.1812 - val_acc: 0.9422
Epoch 2/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.1343 - acc: 0.9580 - val_loss: 0.1541 - val_acc: 0.9534
Epoch 3/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0846 - acc: 0.9723 - val_loss: 0.1400 - val_acc: 0.9572
Epoch 4/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0598 - acc: 0.9807 - val_loss: 0.2322 - val_acc: 0.9380
Epoch 5/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0458 - acc: 0.9847 - val_loss: 0.1460 - val_acc: 0.9662
Epoch 6/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0363 - acc: 0.9882 - val_loss: 0.1496 - val_acc: 0.9608
Epoch 7/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0352 - acc: 0.9887 - val_loss: 0.1661 - val_acc: 0.9604
Epoch 8/10
1875/1875 [==========================

In [108]:
loss, accuracy = model2.evaluate(x_test, reg_test_label)
print(f' Model loss on the test set: {loss}')
print(f' Model accuracy on the test set: {100*accuracy}')

157/157 [==============================] - 0s 3ms/step - loss: 0.1896 - acc: 0.9586
 Model loss on the test set: 0.18957120180130005
 Model accuracy on the test set: 95.85999846458435


In [109]:
predictions = model2.predict(x_test)
pred_arg = np.argmax(predictions, axis=1)

157/157 [==============================] - 1s 3ms/step


In [110]:
from sklearn.metrics import confusion_matrix
cnf_matrix=confusion_matrix(reg_test_label,pred_arg)
print("cnf_matrix_2.0_70")
print("")
print(cnf_matrix)

cnf_matrix_2.0_70

[[469   2   2   1   4   0   4   0   4   1]
 [  1 526   0   1   0   0   1   0   0   0]
 [  6   1 491   2   0   0   5   2   0   0]
 [  0   2  13 478   1   7   1   1   2   1]
 [  1   1   4   0 494   0   4   2   1   5]
 [  2   1   0   7   3 444   7   1   8   0]
 [  2   1   1   0   1   0 481   0   0   0]
 [  0   0   5   0   7   0   0 483   0   7]
 [  3   4   9   5   4   3   3   3 440  12]
 [  2   1   3   2   7   1   0   4   5 487]]


In [111]:
from sklearn.metrics import accuracy_score, recall_score,precision_score,roc_auc_score,roc_curve,f1_score


In [112]:
print(accuracy_score(reg_test_label, pred_arg))
print(f1_score(reg_test_label,pred_arg,average='macro'))
print(recall_score(reg_test_label, pred_arg, average="weighted"))
print(precision_score(reg_test_label, pred_arg, average="weighted"))

0.9586
0.9583436099534545
0.9586
0.958819454652686
